import type { Metadata } from "next";
import { EB_Garamond, Source_Sans_3 } from "next/font/google";
import Script from "next/script";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { BUSINESS } from "@/lib/products";
import "./globals.css";
import { cn } from "@/lib/utils";

const garamond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  style: ["normal", "italic"],
});

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.precursorproperty.com";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Precursor | Property Due Diligence Reports | Victoria",
    template: "%s | Precursor Property",
  },
  description:
    "Independent property due diligence reports for buyers and small developers across Victoria. Zoning, comparable sales, growth signals and development feasibility. A$49 flat, delivered in about 48 hours.",
  keywords: [
    "property due diligence Victoria",
    "buyers due diligence report",
    "development feasibility report",
    "Section 32 review",
    "comparable sales report",
    "subdivision feasibility Victoria",
  ],
  openGraph: {
    type: "website",
    siteName: BUSINESS.name,
    locale: "en_AU",
    // og image is generated by app/opengraph-image.tsx
  },
  twitter: { card: "summary_large_image" },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  // Set GOOGLE_SITE_VERIFICATION in Vercel to verify Search Console without
  // a code change. Omitted from the output entirely when unset.
  ...(process.env.GOOGLE_SITE_VERIFICATION && {
    verification: { google: process.env.GOOGLE_SITE_VERIFICATION },
  }),
  alternates: { canonical: "/" },
};

const orgJsonLd = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  "@id": `${SITE_URL}/#business`,
  name: BUSINESS.name,
  alternateName: "Precursor",
  description:
    "Independent property due diligence reports for investors and small developers across Victoria, Australia.",
  url: `${SITE_URL}/`,
  email: BUSINESS.email,
  areaServed: { "@type": "AdministrativeArea", name: BUSINESS.region },
  serviceType: [
    "Property Due Diligence",
    "Development Feasibility Analysis",
    "Investment Property Research",
  ],
  priceRange: "A$49",
  sameAs: [BUSINESS.instagram, BUSINESS.googleProfile],
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE_URL}/#website`,
  url: `${SITE_URL}/`,
  name: BUSINESS.name,
  description:
    "Independent property due diligence and development feasibility reports for Victoria, Australia.",
  publisher: { "@id": `${SITE_URL}/#business` },
  inLanguage: "en-AU",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en-AU" className={cn("h-full antialiased font-sans", garamond.variable, sourceSans.variable)}>
      <body className="flex min-h-full flex-col">
        {/* Declared here rather than via metadata.alternates.types, because a
            page's own `alternates` replaces the layout's wholesale and every
            page sets its own canonical. React hoists this into <head>. */}
        <link
          rel="alternate"
          type="application/rss+xml"
          title="Precursor Property Guides"
          href={`${SITE_URL}/blog/feed.xml`}
        />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-42ZVB1XCDB"
          strategy="afterInteractive"
        />
        <Script id="ga" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-42ZVB1XCDB');`}
        </Script>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify([orgJsonLd, websiteJsonLd]) }}
        />
        <Header />
        <main className="flex-1 pt-[68px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
